export const DefaultKeybinds = {
  'HidePlayer': 'AltRight',
  'PlayPause': 'Space',
  'Fullscreen': 'KeyF',
  'VolumeUp': 'ArrowUp',
  'VolumeDown': 'ArrowDown',
  'SeekForward': 'ArrowRight',
  'SeekBackward': 'ArrowLeft',
  'SeekForwardSmall': 'Shift+ArrowRight',
  'SeekBackwardSmall': 'Shift+ArrowLeft',
  'SeekForwardLarge': 'Period',
  'SeekBackwardLarge': 'Comma',
  'IncreasePlaybackRate': 'Shift+ArrowUp',
  'DecreasePlaybackRate': 'Shift+ArrowDown',
  'UndoSeek': 'KeyZ',
  'RedoSeek': 'Shift+KeyZ',
  'ResetFailed': 'Backquote',
  'AddDownloader': 'Equal',
  'RemoveDownloader': 'Minus',
  'SkipIntroOutro': 'KeyS',
  'GoToStart': 'Digit0',
  'SubtrackDelete': 'Delete',
  'SubtrackShiftRight': 'BracketRight',
  'SubtrackShiftLeft': 'BracketLeft',
  'SubtrackDownload': 'KeyD',
  'SubtrackToggleResync': 'KeyR',
};
