export const DefaultKeybinds = {
  'HidePlayer': 'AltRight',
  'PlayPause': 'Space',
  'Fullscreen': 'KeyF',
  'WindowedFullscreen': 'KeyW',
  'PictureInPicture': 'KeyP',
  'VolumeUp': 'ArrowUp',
  'VolumeDown': 'ArrowDown',
  'Mute': 'KeyM',
  'SeekForward': 'ArrowRight',
  'SeekBackward': 'ArrowLeft',
  'SeekForwardLarge': 'Period',
  'SeekBackwardLarge': 'Comma',
  'SeekForwardFrame': 'Shift+ArrowRight',
  'SeekBackwardFrame': 'Shift+ArrowLeft',
  'IncreasePlaybackRate': 'Shift+ArrowUp',
  'DecreasePlaybackRate': 'Shift+ArrowDown',
  'UndoSeek': 'KeyZ',
  'RedoSeek': 'Shift+KeyZ',
  'ResetFailed': 'Backquote',
  'AddDownloader': 'Equal',
  'RemoveDownloader': 'Minus',
  'PauseDownloaders': 'BracketLeft',
  'SaveVideo': 'KeyD',
  'Screenshot': 'KeyX',
  'SkipIntroOutro': 'KeyS',
  'NextChapter': 'KeyA',
  'GoToStart': 'Digit0',
  'NextVideo': 'KeyN',
  'PreviousVideo': 'KeyB',
  'ToggleSubtitles': 'KeyC',
  'FlipVideo': 'KeyE',
  'RotateVideo': 'KeyR',
  'ToggleVisualFilters': 'KeyQ',
};

export const KeybindsWithModifiers = [
  'SaveVideo',
];
