// Many thanks to cleanspin. https://github.com/cleanspin/audioprofiles
export const DefaultProfilesData = {
  'type': 'audioProfile',
  'version': 1,
  'profiles': [
    {
      'id': 1,
      'label': 'Flat',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.003,
          'knee': 30,
          'ratio': 12,
          'release': 0.25,
          'threshold': -24,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.37,
        'colorgain': 5,
        'microdelay': 89,
        'lowbypass': 250,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 2,
      'label': 'Podcast Clarity',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 120,
              'gainDb': -1,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 3000,
              'gainDb': 3,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.003,
            'knee': 15,
            'ratio': 5,
            'release': 0.2,
            'threshold': -15,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 120,
              'gainDb': -1,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 3000,
              'gainDb': 3,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.003,
            'knee': 15,
            'ratio': 5,
            'release': 0.2,
            'threshold': -15,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 4,
          'release': 0.25,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.37,
        'colorgain': 5,
        'microdelay': 89,
        'lowbypass': 250,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 3,
      'label': 'Cinematic Immersion',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 50,
              'gainDb': 3,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 10000,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.01,
            'knee': 20,
            'ratio': 2,
            'release': 0.4,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 50,
              'gainDb': 3,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 10000,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.01,
            'knee': 20,
            'ratio': 2,
            'release': 0.4,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 20,
          'ratio': 2,
          'release': 0.3,
          'threshold': -18,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 3,
        'microdelay': 60,
        'lowbypass': 300,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 5,
      'label': 'Lo-Fi',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 200,
              'gainDb': 1,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 5000,
              'gainDb': -2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': false,
            'attack': 0.01,
            'knee': 30,
            'ratio': 2,
            'release': 0.3,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 200,
              'gainDb': 1,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 5000,
              'gainDb': -2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': false,
            'attack': 0.01,
            'knee': 30,
            'ratio': 2,
            'release': 0.3,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 2,
          'release': 0.3,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 4,
        'microdelay': 70,
        'lowbypass': 250,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 6,
      'label': 'EDM',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 60,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 12000,
              'gainDb': 3,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 6,
            'release': 0.25,
            'threshold': -15,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 60,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 12000,
              'gainDb': 3,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 6,
            'release': 0.25,
            'threshold': -15,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 25,
          'ratio': 4,
          'release': 0.3,
          'threshold': -18,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 5,
        'microdelay': 90,
        'lowbypass': 250,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 7,
      'label': 'Bass Enhanced',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 50,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 250,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.008,
            'knee': 20,
            'ratio': 5,
            'release': 0.3,
            'threshold': -16,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 50,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 250,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.008,
            'knee': 20,
            'ratio': 5,
            'release': 0.3,
            'threshold': -16,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.005,
          'knee': 25,
          'ratio': 4,
          'release': 0.2,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.35,
        'colorgain': 4,
        'microdelay': 85,
        'lowbypass': 300,
        'highbypass': 5500,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 8,
      'label': 'Gaming Immersion',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 60,
              'gainDb': 3,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 4,
            'release': 0.3,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 60,
              'gainDb': 3,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 4,
            'release': 0.3,
            'threshold': -20,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 6,
          'release': 0.25,
          'threshold': -18,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 4,
        'microdelay': 80,
        'lowbypass': 200,
        'highbypass': 6000,
        'speakerdistance': 20,
        'headdistance': 70,
      },
    },
    {
      'id': 9,
      'label': 'Balanced Music',
      'channels': [
        {
          'id': 0,
          'gain': 0.85,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 80,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 10000,
              'gainDb': -2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 6,
            'release': 0.3,
            'threshold': -18,
            'gain': 1.1,
          },
        },
        {
          'id': 1,
          'gain': 0.85,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 80,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 10000,
              'gainDb': -2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.005,
            'knee': 20,
            'ratio': 6,
            'release': 0.3,
            'threshold': -18,
            'gain': 1.1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 25,
          'ratio': 4,
          'release': 0.4,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.45,
        'colorgain': 3,
        'microdelay': 90,
        'lowbypass': 300,
        'highbypass': 6000,
        'speakerdistance': 30,
        'headdistance': 80,
      },
    },
    {
      'id': 10,
      'label': 'Acoustic',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'peaking',
              'frequency': 250,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.01,
            'knee': 20,
            'ratio': 2,
            'release': 0.25,
            'threshold': -18,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'peaking',
              'frequency': 250,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.01,
            'knee': 20,
            'ratio': 2,
            'release': 0.25,
            'threshold': -18,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 2,
          'release': 0.25,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 4,
        'microdelay': 70,
        'lowbypass': 250,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 11,
      'label': 'Vocal Boost',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'peaking',
              'frequency': 200,
              'gainDb': -2,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 3000,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.002,
            'knee': 30,
            'ratio': 6,
            'release': 0.2,
            'threshold': -16,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'peaking',
              'frequency': 200,
              'gainDb': -2,
              'q': 1,
            },
            {
              'type': 'peaking',
              'frequency': 3000,
              'gainDb': 4,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 8000,
              'gainDb': 1,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': true,
            'attack': 0.002,
            'knee': 30,
            'ratio': 6,
            'release': 0.2,
            'threshold': -16,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.005,
          'knee': 25,
          'ratio': 4,
          'release': 0.2,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.35,
        'colorgain': 4,
        'microdelay': 85,
        'lowbypass': 300,
        'highbypass': 5500,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 12,
      'label': 'Audiophile - Neutral',
      'channels': [
        {
          'id': 0,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 80,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 12000,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': false,
            'attack': 0.01,
            'knee': 30,
            'ratio': 2,
            'release': 0.3,
            'threshold': -18,
            'gain': 1,
          },
        },
        {
          'id': 1,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [
            {
              'type': 'lowshelf',
              'frequency': 80,
              'gainDb': 2,
              'q': 1,
            },
            {
              'type': 'highshelf',
              'frequency': 12000,
              'gainDb': 2,
              'q': 1,
            },
          ],
          'compressor': {
            'enabled': false,
            'attack': 0.01,
            'knee': 30,
            'ratio': 2,
            'release': 0.3,
            'threshold': -18,
            'gain': 1,
          },
        },
        {
          'id': 2,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 3,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 4,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
        {
          'id': 5,
          'gain': 1,
          'muted': false,
          'solo': false,
          'equalizerNodes': [],
          'compressor': {
            'enabled': false,
            'attack': 0.003,
            'knee': 30,
            'ratio': 12,
            'release': 0.25,
            'threshold': -24,
            'gain': 1,
          },
        },
      ],
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 2,
          'release': 0.3,
          'threshold': -18,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 5,
        'microdelay': 80,
        'lowbypass': 300,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
  ],
};
