// Many thanks to cleanspin. https://github.com/cleanspin/audioprofiles
export const DefaultProfilesData = {
  'type': 'audioProfile',
  'version': 1,
  'profiles': [
    {
      'id': 1,
      'label': 'Flat',
    },
    {
      'id': 2,
      'label': 'Podcast Clarity',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 120,
            'gainDb': -1,
            'q': 1,
          },
          {
            'type': 'peaking',
            'frequency': 3000,
            'gainDb': 3,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.003,
          'knee': 15,
          'ratio': 5,
          'release': 0.2,
          'threshold': -15,
          'gain': 1,
        },
      },
    },
    {
      'id': 3,
      'label': 'Cinematic Immersion',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 50,
            'gainDb': 3,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 10000,
            'gainDb': 2,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.01,
          'knee': 20,
          'ratio': 2,
          'release': 0.4,
          'threshold': -20,
          'gain': 1,
        },
      },
      'crosstalk': {
        'enabled': false,
        'decay': -0.3,
        'colorgain': 3,
        'microdelay': 60,
        'lowbypass': 300,
        'highbypass': 5000,
        'speakerdistance': 25,
        'headdistance': 70,
      },
    },
    {
      'id': 5,
      'label': 'Lo-Fi',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 200,
            'gainDb': 1,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 5000,
            'gainDb': -2,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 2,
          'release': 0.3,
          'threshold': -20,
          'gain': 1,
        },
      },
    },
    {
      'id': 6,
      'label': 'EDM',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 60,
            'gainDb': 4,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 12000,
            'gainDb': 3,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.005,
          'knee': 20,
          'ratio': 6,
          'release': 0.25,
          'threshold': -15,
          'gain': 1,
        },
      },
    },
    {
      'id': 7,
      'label': 'Bass Enhanced',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 50,
            'gainDb': 4,
            'q': 1,
          },
          {
            'type': 'peaking',
            'frequency': 250,
            'gainDb': 2,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.008,
          'knee': 20,
          'ratio': 5,
          'release': 0.3,
          'threshold': -16,
          'gain': 1,
        },
      },
    },
    {
      'id': 8,
      'label': 'Gaming Immersion',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 60,
            'gainDb': 3,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 8000,
            'gainDb': 1,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.005,
          'knee': 20,
          'ratio': 4,
          'release': 0.3,
          'threshold': -20,
          'gain': 1,
        },
      },
    },
    {
      'id': 9,
      'label': 'Balanced Music',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 80,
            'gainDb': 2,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 10000,
            'gainDb': -2,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.005,
          'knee': 20,
          'ratio': 6,
          'release': 0.3,
          'threshold': -18,
          'gain': 1.1,
        },
      },
    },
    {
      'id': 10,
      'label': 'Acoustic',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'peaking',
            'frequency': 250,
            'gainDb': 2,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 8000,
            'gainDb': 1,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.01,
          'knee': 20,
          'ratio': 2,
          'release': 0.25,
          'threshold': -18,
          'gain': 1,
        },
      },
    },
    {
      'id': 11,
      'label': 'Vocal Boost',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'peaking',
            'frequency': 200,
            'gainDb': -2,
            'q': 1,
          },
          {
            'type': 'peaking',
            'frequency': 3000,
            'gainDb': 4,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 8000,
            'gainDb': 1,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': true,
          'attack': 0.002,
          'knee': 30,
          'ratio': 6,
          'release': 0.2,
          'threshold': -16,
          'gain': 1,
        },
      },
    },
    {
      'id': 12,
      'label': 'Audiophile - Neutral',
      'master': {
        'id': 'master',
        'gain': 1,
        'mono': false,
        'equalizerNodes': [
          {
            'type': 'lowshelf',
            'frequency': 80,
            'gainDb': 2,
            'q': 1,
          },
          {
            'type': 'highshelf',
            'frequency': 12000,
            'gainDb': 2,
            'q': 1,
          },
        ],
        'compressor': {
          'enabled': false,
          'attack': 0.01,
          'knee': 30,
          'ratio': 2,
          'release': 0.3,
          'threshold': -18,
          'gain': 1,
        },
      },
    },
  ],
};
