export const DOMElements = {
  playerContainer: document.querySelector('.mainplayer'),
  videoContainer: document.querySelector('.mainplayer .video-container'),
  controlsContainer: document.querySelector('.mainplayer .fluid_controls_container'),
  controlsLeft: document.querySelector('.mainplayer .fluid_controls_left'),
  playPauseButton: document.querySelector('.mainplayer .fluid_control_playpause'),
  playPauseButtonBig: document.querySelector('.mainplayer .fluid_control_playpause_big'),
  playPauseButtonBigCircle: document.querySelector('.mainplayer .fluid_control_playpause_big_circle'),
  progressContainer: document.querySelector('.mainplayer .fluid_controls_progress_container'),
  currentProgress: document.querySelector('.mainplayer .fluid_controls_currentprogress'),
  fullscreen: document.querySelector('.mainplayer .fluid_control_fullscreen'),
  windowedFullscreen: document.querySelector('.mainplayer .fluid_control_windowed_fullscreen'),
  subtitles: document.querySelector('.mainplayer .fluid_control_subtitles'),
  videoSource: document.querySelector('.mainplayer .fluid_control_video_source'),
  videoSourceList: document.querySelector('.mainplayer .fluid_video_sources_list'),
  playbackRate: document.querySelector('.mainplayer .fluid_button_playback_rate'),
  playbackRateBanner: document.querySelector('.mainplayer .rate_menu_banner'),
  download: document.querySelector('.mainplayer .fluid_button_download.main_download'),
  saveNotifBanner: document.querySelector('#save_notif_banner'),
  screenshot: document.querySelector('.mainplayer .fluid_button_screenshot'),
  pip: document.querySelector('.mainplayer .fluid_button_pip'),
  duration: document.querySelector('.mainplayer .fluid_control_duration'),
  muteBtn: document.querySelector('.mainplayer .fluid_control_mute'),
  volumeBlock: document.querySelector('.mainplayer .volume_block'),
  volumeBanner: document.querySelector('.mainplayer .volume_banner'),
  volumeControlBar: document.querySelector('.mainplayer .fluid_control_volume'),
  volumeContainer: document.querySelector('.mainplayer .fluid_control_volume_container'),
  volumeUnity: document.querySelector('.mainplayer .unity_volume_marker'),
  currentVolumeText: document.querySelector('.mainplayer .current_volume_text'),
  currentVolume: document.querySelector('.mainplayer .fluid_control_currentvolume'),
  currentVolumePos: document.querySelector('.mainplayer .fluid_control_volume_currentpos'),
  duration: document.querySelector('.mainplayer .fluid_control_duration'),

  seekPreview: document.querySelector('.mainplayer .seek_preview'),
  seekPreviewText: document.querySelector('.mainplayer .seek_preview_text'),
  seekPreviewVideo: document.querySelector('.mainplayer .seek_preview_video'),
  seekPreviewTip: document.querySelector('.mainplayer .seek_preview_tip'),

  progressLoadedContainer: document.querySelector('.mainplayer .progress_loaded_container'),

  subtitlesMenu: document.querySelector('.mainplayer .subtitles_menu'),
  subtitlesView: document.querySelector('.mainplayer .subtitles_view'),
  subtitlesOptions: document.querySelector('.mainplayer .subtitles_options'),
  subtitlesList: document.querySelector('.mainplayer .subtitles_list'),
  subtitlesContainer: document.querySelector('.mainplayer .fluid_subtitles_container'),

  subtitlesOptionsBackButton: document.querySelector('.mainplayer .subtitles_options_back'),
  subtitlesOptionsList: document.querySelector('.mainplayer .subtitles_options_list'),
  subtitlesOptionsTestButton: document.querySelector('.mainplayer .subtitles_test_button'),

  statusMessages: document.querySelectorAll('.mainplayer .status_message'),
  resetFailed: document.querySelector('.mainplayer .reset_failed'),
  skipSegmentsContainer: document.querySelector('.mainplayer .intro_outro_container'),

  skipButton: document.querySelector('.mainplayer .skip_button'),

  markerContainer: document.querySelector('.mainplayer .marker_container'),

  rateMenu: document.querySelector('.mainplayer .rate_menu'),
  playbackRateMenuContainer: document.querySelector('.mainplayer .rate_menu_container'),

  settingsButton: document.querySelector('.mainplayer .fluid_button_settings'),

  linkButton: document.querySelector('.mainplayer .fluid_button_link'),
  subuiContainer: document.querySelector('.mainplayer .subui_container'),
  linkuiContainer: document.querySelector('.mainplayer .linkui_container'),

  bufferingSpinner: document.querySelector('.mainplayer .buffering_spinner'),
  timelineSyncer: document.querySelector('.mainplayer .fluid_controls_timeline_syncer'),

  optionsContainer: document.querySelector('.mainplayer .options_container'),
  audioConfigContainer: document.querySelector('.mainplayer .audio_config_container'),
  audioConfigBtn: document.querySelector('.mainplayer .fluid_button_soundwave'),
  hideButton: document.querySelector('.mainplayer .hide_button'),
  playinfo: document.querySelector('.mainplayer .playinfo'),

  languageButton: document.querySelector('.mainplayer .fluid_control_language'),
  languageMenu: document.querySelector('.mainplayer .fluid_control_language .fluid_language_list'),
  toolsContainer: document.querySelector('.mainplayer .fluid_controls_right'),
  disabledTools: document.querySelector('.mainplayer .fluid_controls_disabled_tools'),
  moreButton: document.querySelector('.mainplayer .fluid_control_more'),
  loopButton: document.querySelector('.mainplayer .fluid_control_loop'),
  loopMenu: document.querySelector('.mainplayer .loop_menu'),
  skipForwardButton: document.querySelector('.mainplayer .fluid_control_skip_forward'),
  skipBackwardButton: document.querySelector('.mainplayer .fluid_control_skip_backward'),

  dragDemoTutorial: document.querySelector('.mainplayer .fluid_controls_dragdemo'),
};
