name: Build and upload artifacts

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      - "V*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: built/*.zip
